src/app.rs, src/data.rs, src/main.rs
This PR splits the metadata (all strings/fields) out of `Item` and `SlotTile`. There are now two new types:
* `ItemMeta`: the metadata for an `Item`
* `SlotMetaTile`: the collected metadata for all `Item`s in a `SlotTile`
Because we don't need this until we hover or perform an action like a search, we can lazy-load the metadata and make the app more responsive. As the metadata gets richer, these benefits are expected to grow.
This isn't 100% ready yet because I ran into some trouble with the borrow checker in `app.rs` and the current solution is a bit of a hack.
=> Split metadata out of Item/SlotTile

src/app.rs
Using the left and right arrow keys will go backwards and forwards through your zoom interval history.
=> feat(zoom): Allows tapping through zoom intervals

src/data.rs, src/deferred_data.rs, src/http/server.rs, src/main.rs
This permits the `DataSource` HTTP server to serve requests in parallel.
=> Make DataSource immutable to enable concurrent access

TODO.md, src/app.rs, src/data.rs, src/main.rs, src/timestamp.rs
This is a refactored/modified version of #17. Notable changes:
* Search is disentangled from draw code. The search routine now:
1. Fetches all meta tiles. We do this up front because we know we'll need all of them.
2. Searches all tiles to generate a cache. Again this happens up front.
3. Now the cache is populated so we can display and highlight separately.
* Search is now done on a tile-by-tile basis. This makes it work with the asynchronous data fetch as results are streaming in. It also helps minimize the size of the cache by reusing common data (e.g., `EntryID`).
* One huge advantage of not messing with the draw code is that now we don't need to deoptimize the culling algorithm, even when search is enabled. In the past, we needed this to implement vertical scroll to item (because the …
=> Add search interface (refactored)

src/app.rs, src/archive_data.rs, src/data.rs, src/deferred_data.rs, src/http/client.rs, src/http/server.rs, src/main.rs, src/parallel_data.rs
Modifies DataSource interface to fold TileSet into DataSourceInfo to save one request and simplify initialization.
=> Use the tile set to render static profiles

TODO.md
Included some of my own wishlist items, plus items from https://github.com/StanfordLegion/legion/issues/1551 and https://github.com/StanfordLegion/prof-viewer/issues/25
=> Add suggested TODO items

src/app.rs
This PR adds support for having the ESC key reset the UI. cc @lightsighter 
Reset includes:
* clearing controls help
* clearing profile filter selections
* clearing any hovers generated by clicking spans
This PR also applies some clippy fixes related to `or_default`.
cc @elliottslaughter if there is some better approach that does not requires passing the windows list through, please let me know.
=> Allow ESC to reset UI

src/file_data.rs, src/lib.rs
The intended use case is to be able to "attach" to archives that happen to be located on a local disk, e.g.:
```
legion_prof --attach legion_prof.0 legion_prof.1
```
So you no longer have to host these over a webserver if you don't want to.
=> Add a FileDataSource that fetches archive files from local disk

Cargo.lock, Cargo.toml, src/app.rs
This PR adds checkbox option to the search that supports only returning results for whole-word matches. 
* closes #31 
cc @elliottslaughter @lightsighter 
---
Searching for "64" with the whole-word option unchecked yields many results, including ones with 64 in the middle of words:
Checking the whole-word option updates to fewer results that only have "64" as an entire word:
=> Add option for whole-word search

Cargo.toml, src/data.rs, src/lib.rs, src/merge_data.rs
This PR adds a new `MergeDeferredDataSource` that combines multiple data sources into a single logical data source. There are a couple of use cases this addresses:
1. Very large profiles may not fit in the memory of any one machine. Now you can slice those profiles into pieces, `--serve` them on different nodes, and `--attach` them all, stitching them back into a single logical profile.
2. When running Legion as a per-rank runtime within MPI, Legion produces N distinct profiles. Then you can use this mode to stitch them back together.
There's an accompanying backend change that goes along with this that I'm still working on. This change introduces the basic `MergeDeferredDataSource` as a building block that those changes can sit on top of.
Known limitations:
* The tile sets need to be …
=> Add a MergeDeferredDataSource which combines multiple data sources

Cargo.lock, Cargo.toml, src/app.rs, src/data.rs, src/deferred_data.rs, src/file_data.rs, src/http/client.rs, src/main.rs, src/merge_data.rs, src/parallel_data.rs
This PR adds a new `DataSourceDescription` struct with a `source_locator` attribute that can be displayed as the app title when present. A corresponding PR will be needed in the frontend to actually compute a common prefix and add it to `StateDataSource`. 
The PR resulted from a good amount of just following the compiler and making things fit, but I have doubts about some of the changes, comments inline @elliottslaughter.
=> [WIP] Plumbing for source locator

src/app.rs
This PR makes the view avoid requesting tiles outside the profile `total_interval`, which can otherwise lead to crashes.
fixes: #39 
cc @elliottslaughter
=> don't request tiles outside the total profile interval

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, src/app.rs
Introduces some new keyboard features we're not using yet, but could potentially take advantage of. See e.g.: https://docs.rs/egui/latest/egui/struct.KeyboardShortcut.html
Egui 0.26 causes issues with click-and-drag, so sticking with 0.25 for now.
=> Upgrade to egui 0.25

TODO.md, src/app.rs
This has two changes:
* When scrolling to an item with an unknown row, do a second scroll once we discover what that row is so that the item stays in the center of the screen
* Pop up a window with item details after the user clicks "Zoom to Item". The window will initially be empty but will populate once the metadata is available.
=> Fix vertical scroll to item when row is unknown, and pop up window with item details

src/timestamp.rs
Intervals are exclusive so they do not include the nanosecond at `stop`.
=> Fix for interval overlap check

src/app.rs
A new scrollbar style was added in egui 0.24 (see https://github.com/emilk/egui/pull/3539), but it's not clickable with our canvas. Probably we're missing with the hit detection, but it's easier to just shut it off.
=> Restore solid scroll bar style from egui pre-0.24

src/archive_data.rs
Generate an index.html for the archive format so we can load on click on sapling instead of having to copy/paste a url.
=> Generate index.html for archive format.

src/app.rs
Make sure that we don't collapse an empty row down below one line in height.
Note: I believe that the first column (the labels) will always be expanded to avoid wrapping, so therefore it isn't necessary to consider text wrapping in this case.
=> Ensure we always render each table row at least one line high

src/app.rs
Egui uses the app key to determine the storage location for persisted configuration files. This does not work well when the app key is something like `~/Downloads/prof_0.gz - Legion Prof` (the case when profiling files you've just downloaded), which results in the app.ron files being persisted to some random subdirectory of `~/Downloads` instead of `~/Library/Application Support/Legion Prof` or something similar (depending on the OS).
So split the app key off from the viewport title so that the former can be short and predictable and not mess with the persistent config location so badly.
=> Split app key from viewport title to stop spraying `app.ron` files everywhere

src/data.rs, src/deferred_data.rs, src/main.rs
In practice we always use plain `DataSource` anyway for compatibility with `ParallelDeferredDataSource`, so remove the unnecessary interface and move the test `DataSource` in main over to the plain interface.
=> Remove `DataSourceMut`

src/app.rs, src/data.rs, src/main.rs, src/merge_data.rs
Every field now consists of a `FieldID`, `Field`, and `Option<Color32>`. If the color is `Some(_)` then the field will be rendered as that color in the UI.
In the current version of this PR, this applies both to pop-ups that are displayed on hover, as well as the pop-up box that appears when you click. Both the field title and field data will be rendered in the specified color.
=> Add color to each field

.github/workflows/rust.yml
To help catch possible build failures on macOS, we now run a version of the `check` job on Mac.
=> Check build on macOS

Cargo.lock, Cargo.toml, src/lib.rs, src/nvtxw.rs
This PR contains the second iteration of our NVTXW export feature. The new code looks significantly different than before, keeping in mind the feedback you've given so far. We may still revise some details of these changes, particularly where the Rust code is perhaps too C-like, but overall it is ready for review. It is at a point where getting the code reviewed by someone with more Rust experience will help inform us how we want to finalize it.
I've marked this PR as a draft while we determine where we will put the crate. For review and CI purposes, I've set it up in the subdir `crate-tmp`, but this is temporary. If you have any feedback to offer on the crate in addition to the Legion Prof Viewer code itself, we would definitely appreciate that, since we are new to Rust and still …
=> Implement NVTXW export

src/app.rs
If you zoom in far enough, you can view an interval 0 ns in duration. This degenerate situation resulted in a divide by zero when calculating the optimal zoom level for static profiles, but there is nothing to show anyway so just return the empty set.
=> Fix a crash when viewing an empty interval on a static profile

src/app.rs, src/archive_data.rs, src/deferred_data.rs, src/http/client.rs, src/merge_data.rs, src/nvtxw.rs, src/parallel_data.rs
Addresses part of #78.
The data pathway for tiles now tracks errors all the way through to the app, where they can be displayed if something went wrong.
=> Handle errors when fetching tiles

src/app.rs
Fixes #30.
When searching collapsed entries, we need to be sure to invalidate if the view interval changes.
=> Check for valid data before inflating slot metas for search

Cargo.lock, Cargo.toml, src/app.rs, src/data.rs, src/deferred_data.rs, src/timestamp.rs
Not sure how to tune it, but right now it is configured to maintain up to 1024 tiles each for summary, slot and slot meta.
=> Add an LRU cache on data source

src/http/client.rs, src/http/mod.rs, src/http/url.rs
Partially addresses #78.
This addresses a common failure mode where the user forgets to type the trailing `/`, resulting in the viewer failing to start. Because we know that profiles are *always* directories we can add this `/` unconditionally without fear of causing problems.
=> Always add trailing slash to URL if not provided by user

src/main.rs
Updated behavior:
* Native: read all command line arguments (instead of just one) as URLs to load
* Web: read all query parameters that start with `url` (`url1`, `url2`, etc.) as URLs to load
=> Load multiple data sources provided in arguments

src/app/core.rs, src/app/mod.rs, src/app/tile_manager.rs, src/timestamp.rs
This PR substantially refactors and improves the tile management in the viewer. Notable changes:
* The entire tile selection infrastructure has been moved into its own struct `TileManager`, with unit tests
* Cache invalidation is centralized and the new algorithm maintains tiles that are shared in common between old and new tile sets. This eliminates flickering when the tile sets can be partially or fully reused
* Fixed a bug in the cache tracking that prevented cache entries from being reused
* The algorithm for choosing tile sets for dynamic profiles has been entirely rewritten:
* When making a new request, the request interval is used directly. There is no point in over-fetching, as the tiles are generated dynamically.
* On subsequent requests, the previous tile set is reused if: (a) …
=> Improve tile manager algorithm

Cargo.lock, Cargo.toml, src/app/core.rs
Fixes #71.
Notable updates:
* Worked around https://github.com/emilk/egui/pull/3860 in egui 0.26 which prevented overlapping rectangles from receiving responses
=> Upgrade to egui 0.26

examples/random_data.rs, src/app/core.rs, src/data.rs, src/merge_data.rs
Fixes profiles from before colors were added to the field tuple in `ItemMeta`. Note this is an API change but makes our serializer compatible with older profiles.
=> Fix for loading older profiles, pre-color

examples/random_data.rs, src/app/core.rs, src/archive_data.rs, src/data.rs, src/deferred_data.rs, src/file_data.rs, src/http/client.rs, src/main.rs, src/merge_data.rs, src/nvtxw.rs, src/parallel_data.rs
Other changes:
* `DataSource` now returns `data::Result` so that errors can be reported.
* `fetch_info` now returns `data::Result` so that errors can be reported.
* `FileDataSource` reports errors rather than crashing.
* `HttpClientDataSource` reports errors for `fetch_info` rather than crashing.
Breaking API change.
Partially address #94 (in the crate binary `main`).
=> Load profiles from disk when URL parsing fails

src/file_data.rs
Actually print out the path that is causing problems, in addition to the error.
=> Better error messages for file_data

src/http/fetch_native.rs, src/http/fetch_web.rs
This enables them to be passed fully through the infrastructure so we don't just crash when a request fails.
=> Foward errors from failed HTTP requests

src/http/client.rs
In order to correctly parse new and old profiles, we have to first attempt to decode the result as `data::Result<T>`, and then a second time as plain `T`.
Previously we were missing the first, and newer profiles did not decode at all. I missed the error before because the `Result` type generated by the nice error message was fully pluggable with the rest of the system. The new code is much more explicit about what type we're decoding.
=> Properly support decoding profiles with/without Result

.cargo/config.toml, .github/workflows/rust.yml, Cargo.lock, Cargo.toml, src/app/core.rs, src/main.rs
* Removes dependence on web_sys unstable APIs (which prevented upgrades)
* egui tooltip code works properly now, so we can remove a lot of custom code in popups
* Set tooltip ID properly so that each item's tooltip is sized separately
* Finally (!) upgrade all dependencies now that we are unblocked on web_sys
=> Upgrade to egui 0.29

.github/workflows/pages.yml, .github/workflows/rust.yml
* Remove `actions-rs` actions because they are now archived
* For `cargo` commands, just run them directly
* For toolchain actions, use `dtolnay`'s replacement
* Cache all build artifacts for faster CI
* Upgrade to `actions/checkout@v4`
* Remove a bunch of self-explanatory build step names
=> Modernize GitHub Actions

src/arrow_data.rs, src/duckdb_data.rs
Sometimes we encounter an empty `Vec` with no hint about what should go inside it. In these cases, we have to generate a dummy entry so we have *something* in the database.
Also add an upgrade path so once a real value comes along we can harmonize the dummy and real values.
Note: this PR contains a workaround for https://github.com/duckdb/duckdb/issues/17803 since apparently lambdas are broken in DuckDB.
=> Fix empty Vec in DuckDB database
